language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly
notifications:
  email: false
env:
   - PYTHON=""
after_success:
- julia -e 'using Pkg;
            Pkg.add("Coverage");
            using Coverage;
            Codecov.submit(Codecov.process_folder())'
